# Generated by Django 4.2.11 on 2024-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('fullTime', 'Full Time'), ('partTime', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('job_postedby', models.CharField(max_length=100)),
            ],
        ),
    ]
