# Generated by Django 4.2.11 on 2024-03-21 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_createdtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
