# Generated by Django 4.2.11 on 2024-03-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0003_recruiter_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
