# Generated by Django 4.2.11 on 2024-03-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0004_alter_recruiter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
