# Generated by Django 4.2.11 on 2024-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
